### ISSUE TITLE
Can't build Android version of HelloXR on macOS with M1 chip

### ISSUE THREAD

**Issue by utzcoz** [KhronosGroup/OpenXR-SDK-Source#327]
Looks like lint task uses old JNA library that doesn't support M1. The stacktrace is here: 

```
> Task :lint
WARN: Unable to load JNA library (OS: Mac OS X 12.***)
java.lang.UnsatisfiedLinkError: /Users/***/Library/Caches/JNA/temp/jna***.tmp: dlopen(/Users/***/Library/Caches/JNA/temp/jna***.tmp, 0x0001): tried: '/Users/***/Library/Caches/JNA/temp/jna***.tmp' (fat file, but missing compatible architecture (have (i386,x86_64), need (arm64e)))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.intellij.jna.JnaLoader.load(JnaLoader.java:16)
	at com.intellij.jna.JnaLoader.isLoaded(JnaLoader.java:29)
	at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:54)
	at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:46)
	at com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:62)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:44)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
	at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:61)
	at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:54)
```
From https://issuetracker.google.com/issues/185057615, we know it was fixed from AGP 7.x. Maybe bumping AGP to 7.x for HelloXR can fix this problem, and enable HelloXR Android version's build on macOS with M1. I know there are many folks have switched to use M1 machine as their development machine on Android part.

**Comment by utzcoz** [comment]
Hi @rpavlik , is there a plan to upgrade OpenXR project's AGP version? I think it can help to resolve this issue.

**Comment by rpavlik** [comment]
Yeah, I'll do it if you don't get to it first 😁 I didn't realize you had listed that in here as the solution.
